### ISSUE TITLE
App not connecting to ElasticSearch

### ISSUE THREAD

**Issue by NihalPratap** [spalger/elasticsearch-angular-example#5]
when i run this app i get the following error....

elasticsearch.angular.min.js:7 Uncaught Error: Cannot find module '__browserify_process'
index.html:33 
Uncaught ReferenceError: require is not defined
angular.js:4587 
Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.5.5/$injector/modulerr?p0=ExampleApp&p1=Error…search-angular-example%2Fnode_modules%2Fangular%2Fangular.min.js%3A21%3A19)

please help...

**Comment by spalger** [comment]
Can you give this another shot? I think it was an issue with the old build and it should be fixed if you start fresh. Thanks!

**Comment by NihalPratap** [comment]
I am running ElasticSearch version 1.7.2....older build in the sense should I upgrade It to 2.x??

**Comment by spalger** [comment]
You should be ble to set the [`apiVersion`](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/configuration.html#config-api-version) to '1.7' for now, but I do recommend upgrading

**Comment by NihalPratap** [comment]
still have the same problem...should i make any changes in the elasticsearch configuration file other than that you have mentioned???

**Comment by spalger** [comment]
If you're still seeing the `Cannot find module '__browserify_process'` then you must still have the old dependencies. Can you try starting from scratch? Delete the old checkout of this repository and start there?

**Comment by NihalPratap** [comment]
yes i installed it fresh once again...i'll check if the problem persists

**Comment by NihalPratap** [comment]
i got this error even with the http:cors enabled...

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://localhost:9200/elastic/_search?size=50. This can be fixed by moving the resource to the same domain or enabling CORS.

how do i resolve this???

**Comment by spalger** [comment]
What is your elasticsearch config?

**Comment by NihalPratap** [comment]
i solved the above problem somehow....now i'm facing a new problem. All the things run perfectly but the output is not displayed on the page..but if i log the result it is displayed on the console.
